In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

%matplotlib inline

In [2]:
from sklearn.metrics import accuracy_score, precision_score, recall_score,f1_score, confusion_matrix

a) Write code to read the dataset in Data Q1.txt into two numpy arrays: X and y containing
the features and labels respectively.

In [3]:
import numpy as np
from urllib.request import urlopen

url = 'https://raw.githubusercontent.com/Saurabh9687/IE-506--2-/main/Data_Q1.txt'

In [4]:
from sklearn.datasets import load_svmlight_file

with urlopen(url) as f:
    X, y = load_svmlight_file(f)

X = X.toarray().astype('int32')
y = y.astype('int32')
print("Label",y)
print("Features",X)

Label [ 1 -1 -1 ...  1 -1  1]
Features [[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 1 1]
 [0 0 0 ... 0 0 0]]


In [5]:
print("Dataset has {} samples".format(*X.shape))

Dataset has 4143 samples


b) Print the number of classes in the data set and the number of samples belonging to
each class. Indicate if there is class imbalance issue.

In [6]:
unique_values = np.unique(y)
count = len(unique_values)
print("Number of classes = ",count)
count1 = np.sum(y==1)
count2 = np.sum(y==-1)
print("number of samples belonging to class 1 = ",count1)
print("number of samples belonging to class -1 = ",count2)

Number of classes =  2
number of samples belonging to class 1 =  2210
number of samples belonging to class -1 =  1933


**No , there is no class imbalance issue.**


C) Split the data into two sets such that 80% of the data is considered as set T1 and
20% of the data is considered as set T2. Justify if set T1 and set T2 have similar class label proportions.
2

In [7]:
from sklearn.model_selection import train_test_split

T1_X, T2_X, T1_y, T2_y = train_test_split(X, y, test_size = 0.20, random_state = 42)

In [8]:
count_T1_1 = np.sum(T1_y==1)
count_T2_1 = np.sum(T2_y==1)
count_T1_2 = np.sum(T1_y==-1)
count_T2_2 = np.sum(T2_y==-1)
print("In set T1 number of samples belonging to class 1 = ",count_T1_1)
print("In set T1 number of samples belonging to class -1 = ",count_T1_2)
print("In set T2 number of samples belonging to class 1 = ",count_T2_1)
print("In set T2 number of samples belonging to class -1 = ",count_T2_2)
print("Label proportion in T1 = ",count_T1_1/count_T1_2)
print("Label proportion in T1 = ",count_T2_1/count_T2_2)

In set T1 number of samples belonging to class 1 =  1762
In set T1 number of samples belonging to class -1 =  1552
In set T2 number of samples belonging to class 1 =  448
In set T2 number of samples belonging to class -1 =  381
Label proportion in T1 =  1.1353092783505154
Label proportion in T1 =  1.1758530183727034


**So, set T1 and set T2 have quite similar class label proportions.**


d) Using T1 as training data, train each of the following algorithms by tuning only the
hyperparameters specified below (keep all other hyperparameters fixed to the default values in
scikit-learn):

In [9]:
train_X, train_y = T1_X, T1_y
test_X, test_y = T2_X, T2_y

In [10]:
def sensitivity_score(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    sensitivity = tp / (tp + fn)
    return sensitivity

In [11]:
def specificity_score(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    specificity = tn / (tn + fp)
    return specificity

In [12]:
def matrix(train_y,pred_train,test_y,pred):
  accuracy_T1 = accuracy_score(train_y,pred_train)
  precision_T1 = precision_score(train_y,pred_train)
  recall_T1 = recall_score(train_y,pred_train)
  specificity_T1 = specificity_score(train_y,pred_train)
  sensitivity_T1 = sensitivity_score(train_y,pred_train)
  accuracy_T2 = accuracy_score(test_y,pred)
  precision_T2 = precision_score(test_y,pred)
  recall_T2 = recall_score(test_y,pred)
  specificity_T2 = specificity_score(test_y,pred)
  sensitivity_T2 = sensitivity_score(test_y,pred)
  return  accuracy_T1, precision_T1, recall_T1, specificity_T1, sensitivity_T1, accuracy_T2, precision_T2, recall_T2, specificity_T2,sensitivity_T2

i) Logistic regression with L2 regularizer (Hyperparameter: regularization constant C)

For smaller datasets, we would use smaller ranges and perform a more targeted search, while for larger datasets, we would consider larger ranges and perform a more broad search.

Higher values of C lead to less regularization, while lower values lead to more regularization.

Considering a range of values for C from 0.1 to 10, with a logarithmic spacing.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

lg_l2 = LogisticRegression(penalty="l2", max_iter=10000)
param_grid = {'C':np.logspace(-1, 1, 3)}

CV_lg_l2 = GridSearchCV(estimator=lg_l2, param_grid=param_grid, cv= 5, n_jobs=-1)
CV_lg_l2.fit(train_X, train_y)
best_C = CV_lg_l2.best_params_['C']
print(CV_lg_l2.best_params_)

In [ ]:
from sklearn.metrics import accuracy_score

lg_l2_1=LogisticRegression(penalty="l2",C = best_C)
lg_l2_1.fit(train_X, train_y)
pred_lg_l2=lg_l2_1.predict(test_X)
print("Accuracy for Logistic Regression with L2 regularizer on CV data: ",accuracy_score(test_y,pred_lg_l2))

In [ ]:
lg_l2_1.fit(train_X, train_y)
pred_train_lg_l2=lg_l2_1.predict(train_X)

In [ ]:
accuracy_lg_l2_T1, precision_lg_l2_T1, recall_lg_l2_T1, specificity_lg_l2_T1, sensitivity_lg_l2_T1, accuracy_lg_l2_T2, precision_lg_l2_T2, recall_lg_l2_T2, specificity_lg_l2_T2,sensitivity_lg_l2_T2 = matrix(train_y,pred_train_lg_l2,test_y,pred_lg_l2)

ii) Logistic regression with L1 regularizer (Hyperparameter: regularization constant C)

Higher values of C lead to less regularization, while lower values lead to more regularization.

Considering a range of values for C from 0.1 to 10, with a logarithmic spacing.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

lg_l1 = LogisticRegression(penalty="l1",solver = 'saga', max_iter=100000)
param_grid = {'C':np.logspace(-1, 1, 3)}

CV_lg_l1 = GridSearchCV(estimator=lg_l1,param_grid=param_grid, cv= 5)
CV_lg_l1.fit(train_X, train_y)
best_C_lg_l1 = CV_lg_l1.best_params_['C']
print(CV_lg_l1.best_params_)

In [ ]:
from sklearn.metrics import accuracy_score

lg_l1_1=LogisticRegression(penalty="l1",C = best_C_lg_l1,solver = 'saga')
lg_l1_1.fit(train_X, train_y)
pred_lg_l1=lg_l1_1.predict(test_X)
print("Accuracy for Logistic Regression with L2 regularizer on CV data: ",accuracy_score(test_y,pred_lg_l1))

In [ ]:
lg_l1_1.fit(train_X, train_y)
pred_train_lg_l1=lg_l1_1.predict(train_X)

In [ ]:
accuracy_lg_l1_T1, precision_lg_l1_T1, recall_lg_l1_T1, specificity_lg_l1_T1, sensitivity_lg_l1_T1, accuracy_lg_l1_T2, precision_lg_l1_T2, recall_lg_l1_T2, specificity_lg_l1_T2,sensitivity_lg_l1_T2 = matrix(train_y,pred_train_lg_l1,test_y,pred_lg_l1)

iii. Soft-margin SVM with L2 regularizer (Hyperparameter: regularization constant C)

Higher values of C lead to less regularization, while lower values lead to more regularization.

Considering a range of values for C from 0.1 to 10, with a logarithmic spacing.

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.svm import LinearSVC

sm_svm_l2 = LinearSVC(penalty="l2", max_iter=100000)
param_grid = {'C':np.logspace(-1, 1, 3)}

CV_sm_svm_l2 = GridSearchCV(estimator=sm_svm_l2, param_grid=param_grid, cv= 5)
CV_sm_svm_l2.fit(train_X, train_y)
best_sm_svm_l2 = CV_sm_svm_l2.best_params_['C']
print(CV_sm_svm_l2.best_params_)

{'C': 0.1}


In [16]:
from sklearn.metrics import accuracy_score

sm_svm_l2=LinearSVC(penalty="l2",C = best_sm_svm_l2)
sm_svm_l2.fit(train_X, train_y)
pred_sm_svm_l2=sm_svm_l2.predict(test_X)
print("Accuracy for Soft-margin SVM with L2 regularizer on CV data: ",accuracy_score(test_y,pred_sm_svm_l2))

Accuracy for Soft-margin SVM with L2 regularizer on CV data:  0.8914354644149578


In [17]:
sm_svm_l2.fit(train_X, train_y)
pred_train_sm_svm_l2=sm_svm_l2.predict(train_X)

In [18]:
accuracy_sm_svm_l2_T1, precision_sm_svm_l2_T1, recall_sm_svm_l2_T1, specificity_sm_svm_l2_T1, sensitivity_sm_svm_l2_T1, accuracy_sm_svm_l2_T2, precision_sm_svm_l2_T2, recall_sm_svm_l2_T2, specificity_sm_svm_l2_T2,sensitivity_sm_svm_l2_T2 = matrix(train_y,pred_train_sm_svm_l2,test_y,pred_sm_svm_l2)

iv. Soft-margin SVM with L1 regularizer (Hyperparameter: regularization constant C)

Higher values of C lead to less regularization, while lower values lead to more regularization.

Considering a range of values for C from 0.1 to 10, with a logarithmic spacing.

In [20]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.svm import LinearSVC

sm_svm = LinearSVC(penalty="l1", max_iter=100000, loss="squared_hinge", dual=False, class_weight='balanced', tol=1e-3,)
param_grid = {'C':np.logspace(-1, 1, 3)}

CV_sm_svm = GridSearchCV(estimator=sm_svm, param_grid=param_grid, cv= 5)
CV_sm_svm.fit(train_X, train_y)
best_sm_svm_l1  = CV_sm_svm.best_params_['C']
print(CV_sm_svm.best_params_)

{'C': 0.1}


In [21]:
from sklearn.metrics import accuracy_score

sm_svm_l1=LinearSVC(penalty="l1",C = best_sm_svm_l1,loss="squared_hinge", dual=False, class_weight='balanced', tol=1e-3, )
sm_svm_l1.fit(train_X, train_y)
pred_sm_svm_l1=sm_svm_l1.predict(test_X)
print("Accuracy for Soft-margin SVM with L1 regularizer on CV data: ",accuracy_score(test_y,pred_sm_svm_l1))

Accuracy for Soft-margin SVM with L1 regularizer on CV data:  0.8926417370325693


In [22]:
sm_svm_l1.fit(train_X, train_y)
pred_train_sm_svm_l1=sm_svm_l1.predict(train_X)

In [23]:
accuracy_sm_svm_l1_T1, precision_sm_svm_l1_T1, recall_sm_svm_l1_T1, specificity_sm_svm_l1_T1, sensitivity_sm_svm_l1_T1, accuracy_sm_svm_l1_T2, precision_sm_svm_l1_T2, recall_sm_svm_l1_T2,specificity_sm_svm_l1_T2, sensitivity_sm_svm_l1_T2 = matrix(train_y,pred_train_sm_svm_l1,test_y,pred_sm_svm_l1)

v. Kernel SVM with RBF kernel (Hyperparameter: kernel parameter γ)

Higher values of gamma lead to more complex decision boundaries, while lower values lead to simpler decision boundaries.

Considering a range of values for gamma from 0.1 to 10, with a logarithmic spacing.

In [ ]:
from sklearn import svm
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

param_grid = {'kernel': ['rbf'], 'gamma': np.logspace(-1, 1, 3)}

svc = svm.SVC( max_iter=10000, class_weight='balanced')
CV_svc = GridSearchCV(estimator=svc, param_grid=param_grid, cv= 5)
CV_svc.fit(train_X, train_y)
best_gamma_svc = CV_svc.best_params_['gamma']

In [ ]:
from sklearn.metrics import accuracy_score

svc1=svm.SVC(gamma=best_gamma_svc)
svc1.fit(train_X, train_y)
pred_svc=svc1.predict(test_X)
print("Accuracy for Kernel SVM with RBF kernel on CV data: ",accuracy_score(test_y,pred_svc))

In [ ]:
svc1.fit(train_X, train_y)
pred_train_svc=svc1.predict(train_X)

In [ ]:
accuracy_svc_T1, precision_svc_T1, recall_svc_T1, specificity_svc_T1, sensitivity_svc_T1, accuracy_svc_T2, precision_svc_T2, recall_svc_T2,specificity_svc_T2, sensitivity_svc_T2 = matrix(train_y,pred_train_svc,test_y,pred_svc)

vi. KNN (Hyperparameter: number of neighbors)

k controls the number of neighbors to consider for each prediction.

Considering a range of values for k from 1 to 6.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV

kNc = KNeighborsClassifier()
param_grid = {'n_neighbors': range(1, 6,2)}
CV_kNc = GridSearchCV(estimator=kNc, param_grid=param_grid, cv= 5)
CV_kNc.fit(train_X, train_y)
best_n_kNc = CV_kNc.best_params_['n_neighbors']

In [ ]:
from sklearn.metrics import accuracy_score

kNc1=KNeighborsClassifier(n_neighbors= best_n_kNc)
kNc1.fit(train_X, train_y)
pred_kNc=kNc1.predict(test_X)
print("Accuracy for KNN on CV data: ",accuracy_score(test_y,pred_kNc))

In [ ]:
kNc1.fit(train_X, train_y)
pred_train_kNc=kNc1.predict(train_X)

In [ ]:
accuracy_kNc_T1, precision_kNc_T1, recall_kNc_T1, specificity_kNc_T1, sensitivity_kNc_T1, accuracy_kNc_T2, precision_kNc_T2, recall_kNc_T2,specificity_kNc_T2, sensitivity_kNc_T2 = matrix(train_y,pred_train_kNc,test_y,pred_kNc)

vii. Decision tree (Hyperparameter: min weight fraction leaf)

minimum weight fraction leaf controls the minimum fraction of samples required to be at a leaf node.

Considering a range of values for the minimum weight fraction leaf from 0 to 0.5, with a step size of 0.1.

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier


dtc = DecisionTreeClassifier()
param_grid = {'min_weight_fraction_leaf': np.arange(0, 0.51, 0.1)}
CV_dtc = GridSearchCV(estimator=dtc, param_grid=param_grid, cv= 5)
CV_dtc.fit(train_X, train_y)
best_dtc = CV_dtc.best_params_['min_weight_fraction_leaf']

In [ ]:
from sklearn.metrics import accuracy_score

dtc1=DecisionTreeClassifier(min_weight_fraction_leaf= best_dtc)
dtc1.fit(train_X, train_y)
pred_dtc=dtc1.predict(test_X)
print("Accuracy for Decesion Tree on CV data: ",accuracy_score(test_y,pred_dtc))

In [ ]:
dtc1.fit(train_X, train_y)
pred_train_dtc=dtc1.predict(train_X)

In [ ]:
accuracy_dtc_T1, precision_dtc_T1, recall_dtc_T1, specificity_dtc_T1, sensitivity_dtc_T1, accuracy_dtc_T2, precision_dtc_T2, recall_dtc_T2,specificity_dtc_T2, sensitivity_dtc_T2 = matrix(train_y,pred_train_dtc,test_y,pred_dtc)

viii. Random forest (Hyperparameter: number of estimators)

The number of estimators controls the number of trees in the forest.

Considering a range of values for the number of estimators from 0 to 150, with a step size of 50.

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

rfc=RandomForestClassifier()
param_grid = {'n_estimators': range(0, 150, 50)}
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(train_X, train_y)
best_rfc = CV_rfc.best_params_


In [ ]:
from sklearn.metrics import accuracy_score

rfc1=RandomForestClassifier(n_estimators= best_dtc)
rfc1.fit(train_X, train_y)
pred_rfc=rfc1.predict(test_X)
print("Accuracy for Random Forest on CV data: ",accuracy_score(test_y,pred_rfc))

In [ ]:
rfc1.fit(train_X, train_y)
pred_train_rfc=rfc1.predict(train_X)

In [ ]:
accuracy_rfc_T1, precision_rfc_T1, recall_rfc_T1, specificity_rfc_T1, sensitivity_rfc_T1, accuracy_rfc_T2, precision_rfc_T2, recall_rfc_T2,specificity_rfc_T2, sensitivity_rfc_T2 = matrix(train_y,pred_train_rfc,test_y,pred_rfc)

e) Tabulate the accuracy, precision, recall, specificity and senstivity values for training
set T1 and test set T2 for each model trained in part (d) for the best hyperparameter choices.
Discuss your observations.

In [ ]:
data = {'Model': ['Logistic regression (L2)','Logistic regression (L1)','Soft-margin SVM (L2)', 'Soft-margin SVM (l1)','Kernel SVM with RBF kernel', 'KNN', 'Decision tree', 'Random forest'],
              'Train Accuracy': [accuracy_lg_l2_T1,accuracy_lg_l1_T1,accuracy_sm_svm_l2_T1,accuracy_sm_svm_l1_T1,accuracy_svc_T1,accuracy_kNc_T1,accuracy_dtc_T1,accuracy_rfc_T1],
              'Train Precision': [precision_lg_l2_T1,precision_lg_l1_T1,precision_sm_svm_l2_T1,precision_sm_svm_l1_T1,precision_svc_T1,precision_kNc_T1,precision_dtc_T1,precision_rfc_T1],
              'Train Recall': [recall_lg_l2_T1,recall_lg_l1_T1,recall_sm_svm_l2_T1,recall_sm_svm_l1_T1,recall_svc_T1,recall_kNc_T1,recall_dtc_T1,recall_rfc_T1],
              'Train Specificity': [specificity_lg_l2_T1,specificity_lg_l1_T1,specificity_sm_svm_l2_T1,sensitivity_sm_svm_l1_T1,sensitivity_svc_T1,sensitivity_kNc_T1,sensitivity_dtc_T1,sensitivity_rfc_T1],
              'Train Sensitivity': [sensitivity_lg_l2_T1,sensitivity_lg_l1_T1,sensitivity_sm_svm_l2_T1,sensitivity_sm_svm_l1_T1,sensitivity_svc_T1,sensitivity_kNc_T1,sensitivity_dtc_T1,sensitivity_rfc_T1],
              'Test Accuracy': [accuracy_lg_l2_T2,accuracy_lg_l1_T2,accuracy_sm_svm_l2_T2,accuracy_sm_svm_l1_T2,accuracy_svc_T2,accuracy_kNc_T2,accuracy_dtc_T2,accuracy_rfc_T2],
              'Test Precision': [precision_lg_l2_T2,precision_lg_l1_T2,precision_sm_svm_l2_T2,precision_sm_svm_l1_T2,precision_svc_T2,precision_kNc_T2,precision_dtc_T2,precision_rfc_T2],
              'Test Recall': [recall_lg_l2_T2,recall_lg_l1_T2,recall_sm_svm_l2_T2,recall_sm_svm_l1_T2,recall_svc_T2,recall_kNc_T2,recall_dtc_T2,recall_rfc_T2],
              'Test Specificity': [specificity_lg_l2_T2,specificity_lg_l1_T2,specificity_sm_svm_l2_T2,specificity_sm_svm_l1_T2,specificity_svc_T2,specificity_kNc_T2,specificity_dtc_T2,specificity_rfc_T2],
              'Test Sensitivity':  [sensitivity_lg_l2_T2,sensitivity_lg_l1_T2,sensitivity_sm_svm_l2_T2,sensitivity_sm_svm_l1_T2,sensitivity_svc_T2,sensitivity_kNc_T2,sensitivity_dtc_T2,sensitivity_rfc_T2]}


df = pd.DataFrame(data)


print(df)

f) Discuss if the L1 regularizers used in logistic regression and soft-margin SVM resulted
in sparse models when compared to L2 regularizers. Also compare and contrast the performance
of the models obtained using L1 and L2 regularizers. Using these observations, what
would you suggest to the practitioner regarding the use of L1 regularizer?

In [ ]:
nonZero_coef_lg_l2 = np.count_nonzero(lg_l2_1.coef)
print("Non Zero Coeff for Logistic regression with L2 regularizer = ",nonZero_coef_lg_l2)

nonZero_coef_lg_l1 = np.count_nonzero(lg_l1_1.coef)
print("Non Zero Coeff for Logistic regression with L1 regularizer = ",nonZero_coef_lg_l1)

nonZero_coef_sm_svm_l2 = np.count_nonzero(sm_svm_l2.coef)
print("Non Zero Coeff for Logistic regression with L2 regularizer = ",nonZero_coef_sm_svm_l2)

nonZero_coef_sm_svm_l1 = np.count_nonzero(sm_svm_l1.coef)
print("Non Zero Coeff for Logistic regression with L1 regularizer = ",nonZero_coef_sm_svm_l1)

L1 and L2 regularization are techniques used in machine learning to prevent overfitting and improve model performance. One key difference between these regularization methods is that L1 regularization encourages sparsity in the model, while L2 regularization does not necessarily lead to sparse models.

To determine if L1 regularizers used in logistic regression and soft-margin SVM resulted in sparse models when compared to L2 regularizers, i am comparing the number of non-zero coefficients in the resulting models above. L1 regularization tends to produce models with fewer non-zero coefficients than L2 regularization. This is because L1 regularization tends to force some coefficients to zero, effectively removing them from the model and resulting in a sparse model.