a) Recall that in ridge regression, we solve the problem minβ
λ
2 ∥β∥22∥+y − Xβ∥22
Using the first order optimality conditions, show that X⊤Xβ + λβ = X⊤y holds, and show
that this can be equivalently written as β = X⊤α where α = 1
λ (y − Xβ). Further show that
α = (X⊤X + λI)−1y. Note that in this relation X⊤X can be effectively replaced by a kernel
matrix using the kernel function idea discussed in class as α = (K + λI)−1y. Now, represent the
inference function ⟨β, x⟩ using α and hence using kernels. This extension to ridge regression is
called kernel ridge regression.

Ridge Regression

$
min_{\beta }\; \frac{\lambda }{2} \left \| \beta  \right \|_{2}^{2} + \left \| y - X\beta  \right \|_{2}^{2}
$

Using the first order optimality condition,

$
L = min_{\beta }\; \frac{\lambda }{2} \left \| \beta  \right \|_{2}^{2} + \left \| y - X\beta  \right \|_{2}^{2}
$  

$
\nabla_{\beta }L = -2(y-X\beta )X^{T} + 2\lambda \beta = \vec{0}
$

$
\nabla_{\beta }L = -2X^{T}y + 2X^{T}X\beta +2\lambda \beta = 0
$

So,

$
\mathbf{X^{T}X\beta +\lambda \beta = X^{T}y}
$

Factoring out β,

$
(X^{T}X + \lambda I)\beta  = X^{T}y
$

Multiplying both sides by 
$
(X^{T}X + \lambda I)^{-1}\;,
$

$
\beta  = (X^{T}X + \lambda I)^{-1}X^{T}y
$

we can express β as:

$
\beta  = X^{T}\alpha \;, where\; \alpha  = \frac{1}{\lambda } (y - X\beta )
$

Substituting 
$
\beta  = Xᵀ\alpha , 
$

$
X^{T}X(X^{T}\alpha ) + \lambda (X^{T}\alpha ) = X^{T}y
$

$
X^{T}X\alpha  + \lambda \alpha  = X^{T}y
$

Factoring out α, 

$
(X^{T}X + \lambda I)\alpha  = X^{T}y
$

Multiplying both sides by
$
 (X^{T}X + \lambda I)^{-1}, 
$

$
\alpha  = \frac{(X^{T}X + \lambda I)^{-1}X^{T}y}{\lambda }
$

Substituting the expression for α back into 
$
\beta = X^{T}\alpha 
$

$
\beta  = X^{T}(X^{T}X + \lambda I)^{-1}X^{T}y
$

which is the same as the solution obtained earlier.








Substituting the value of β in terms of α in the equation 
$
X^{T}Xβ + λβ = X^{T}y, 
$

$
X^{T}X X^{T}α + λX^{T}α = X^{T}y
$

$
α = (X^{T}X + λI)^{-1}y
$

Now, to represent the inference function ⟨β, x⟩ using α, we have:

$
⟨β, x⟩ = x^{T}β = x^{T}X^{T}α = ⟨ϕ(x), X^{T}α⟩
$

where ϕ(x) is the feature map that maps x to the higher dimensional space in which the linear regression is performed. Using the kernel trick, we can represent this as:

$
⟨β, x⟩ = ⟨ϕ(x), β⟩ = ⟨ϕ(x), X^{T}α⟩ = ⟨K(x, ·), α⟩
$

where K(x, ·) is the kernel function that computes the inner product between the feature map of x and the feature map of all the training points. This is the extension to ridge regression known as kernel ridge regression.

In [32]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

%matplotlib inline

In [33]:
from sklearn.kernel_ridge import KernelRidge
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score
from sklearn import svm

b) Reading the data set in Data Q2.csv into a pandas dataframe.

In [34]:
Data_Q2 = pd.read_csv('https://raw.githubusercontent.com/Saurabh9687/IE-506--2-/main/Data_Q2.csv',encoding='unicode_escape', index_col=False, header=None)
Data_Q2.head()

0      1      2      3            4
0   5.578  93.00  0.082  0.185  5935.174070
1  15.510  64.38  0.085  0.133  6044.657863
2  15.730  64.21  0.084  0.152  6061.944778
3  15.620  65.22  0.083  0.145  6108.043217
4  15.450  67.69  0.083  0.189  6119.567827

In [35]:
Data_Q2.columns = ['Temperature','Humidity','Wind Speed','Flow','Consumption']
Data_Q2.head()

Temperature  Humidity  Wind Speed   Flow  Consumption
0        5.578     93.00       0.082  0.185  5935.174070
1       15.510     64.38       0.085  0.133  6044.657863
2       15.730     64.21       0.084  0.152  6061.944778
3       15.620     65.22       0.083  0.145  6108.043217
4       15.450     67.69       0.083  0.189  6119.567827

c) Performing standardization of each column in the data frame and create a new data
frame.

In [36]:
scaler = StandardScaler()
Data_std_arr = scaler.fit(Data_Q2)
Data_std_arr = scaler.transform(Data_Q2)
print(Data_std_arr)

[[-1.93187821  1.40484647 -0.6417913  -0.66437014 -3.45020803]
 [ 0.40765436 -0.87447368 -0.64041729 -0.66572409 -3.28244223]
 [ 0.45947647 -0.88801262 -0.64087529 -0.66522938 -3.2559529 ]
 ...
 [ 0.24276584  0.55268974  1.57082257 -0.66504712  1.93512737]
 [-0.39794384  0.16244974 -0.64591333 -0.66647918  1.93512737]
 [ 0.68325375 -0.83146764 -0.64316531  2.25743913  1.9356659 ]]


In [37]:
Data_std = pd.DataFrame(Data_std_arr, columns=Data_Q2.columns)

d) Splitting the data into two sets T1 and T2 and Justifing if the splits T1 and T2 have similar spread in
Consumption column.

In [38]:
T1, T2= train_test_split(Data_std, test_size = 0.20, random_state=42)

In [39]:
T1_std = np.std(T1)
T2_std = np.std(T2)
print("Standard deviation of the dataset T1 is:", T1_std)
print("Standard deviation of the dataset T2 is:", T2_std)

Standard deviation of the dataset T1 is: Temperature    0.991211
Humidity       1.003977
Wind Speed     1.011473
Flow           1.011137
Consumption    1.009550
dtype: float64
Standard deviation of the dataset T2 is: Temperature    1.034094
Humidity       0.975016
Wind Speed     0.944963
Flow           0.954104
Consumption    0.959361
dtype: float64


So Standard deviation of T1 and T2 dataset for consumption  are quite near so, the splits T1 and T2 have very low spread in
Consumption column.

In [41]:
T1_X = T1.drop('Consumption', axis=1)
T1_y =  T1['Consumption']
T1_y.columns = ['Consumption']
T2_X = T2.drop('Consumption', axis=1)
T2_y = T2['Consumption']
T2_y.columns = ['Consumption']


e) Using T1 as training data, training kernel ridge regression model. Using RBF kernel and
tune the gamma parameter using 5-fold cross-validation.

In [42]:
def kernel_ridge(X,y):
  param_grid = {'kernel': ['rbf'], 'gamma': np.logspace(-5,5,11)}
  kr = KernelRidge()
  CV_kr = GridSearchCV(estimator=kr, param_grid=param_grid, cv= 5)
  CV_kr.fit(X, y)
  return  CV_kr.best_params_['gamma']

In [43]:
print("Best gamma  = ",kernel_ridge(T1_X,T1_y))

Best gamma  =  10.0


f) Computing and displaying the RMSE and R2 values on the training set T1 and test set
T2.

In [44]:
kr1=KernelRidge(kernel='rbf',gamma=10)
kr1.fit(T1_X, T1_y)
pred_T1=kr1.predict(T1_X)

mse_T1 = mean_squared_error(T1_y, pred_T1)
RMSE_T1 = np.sqrt(mse_T1)
r2_T1 = r2_score(T1_y, pred_T1)

print("RMSE value on the training set T1 = ",RMSE_T1)
print("R^2 value on the training set T1 = ",r2_T1)

pred_T2 =kr1.predict(T2_X)

mse_T2 = mean_squared_error(T2_y, pred_T2)
RMSE_T2 = np.sqrt(mse_T2)
r2_T2 = r2_score(T2_y, pred_T2)

print("RMSE value on the test set T2 = ",RMSE_T2)
print("R^2 value on the test set T2 = ",r2_T2)

RMSE value on the training set T1 =  0.6500917245076449
R^2 value on the training set T1 =  0.5853383919265936
RMSE value on the test set T2 =  0.8128918014697996
R^2 value on the test set T2 =  0.2820379758920609


g) Considering the original data in Data Q2.csv and loading it into a different pandas dataframe
called frame2. Adding another column with name Class to the dataframe frame2 according to consumption values.

In [45]:
frame2 = pd.DataFrame(Data_Q2)
frame2['Class'] = [1 if x <= 6500 else 2 if 6500<x<=7000 else 3 if 7000<x<=7500 else 4 if 7500<x<=8000 else 5 if 8000<x<=8500 else 6 if 8500<x<=9000 else 7 for x in frame2['Consumption']]
print(frame2)

     Temperature  Humidity  Wind Speed     Flow  Consumption  Class
0          5.578     93.00       0.082    0.185  5935.174070      1
1         15.510     64.38       0.085    0.133  6044.657863      1
2         15.730     64.21       0.084    0.152  6061.944778      1
3         15.620     65.22       0.083    0.145  6108.043217      1
4         15.450     67.69       0.083    0.189  6119.567827      1
..           ...       ...         ...      ...          ...    ...
995       17.330     42.24       4.917   31.540  9443.855422      7
996        7.010     76.40       4.920   65.890  9449.638554      7
997       14.810     82.30       4.913    0.159  9449.638554      7
998       12.090     77.40       0.073    0.104  9449.638554      7
999       16.680     64.92       0.079  112.400  9449.990000      7

[1000 rows x 6 columns]


h) Performing standardization of samples in frame2 belonging to each class separately.
Ignoring Class column during standardization procedure.

In [46]:
def Standardisation(Data):
  cols_to_norm = ['Temperature', 'Humidity', 'Wind Speed', 'Flow', 'Consumption']
  scaler = StandardScaler()
  Std_Data = scaler.fit(Data[cols_to_norm])
  Std_Data = scaler.transform(Data)
  return Std_Data

In [47]:
frame2_new = frame2.drop('Class',axis=1)
frame2_new

Temperature  Humidity  Wind Speed     Flow  Consumption
0          5.578     93.00       0.082    0.185  5935.174070
1         15.510     64.38       0.085    0.133  6044.657863
2         15.730     64.21       0.084    0.152  6061.944778
3         15.620     65.22       0.083    0.145  6108.043217
4         15.450     67.69       0.083    0.189  6119.567827
..           ...       ...         ...      ...          ...
995       17.330     42.24       4.917   31.540  9443.855422
996        7.010     76.40       4.920   65.890  9449.638554
997       14.810     82.30       4.913    0.159  9449.638554
998       12.090     77.40       0.073    0.104  9449.638554
999       16.680     64.92       0.079  112.400  9449.990000

[1000 rows x 5 columns]

In [48]:
Data_class1 = frame2_new[frame2['Class']==1]
Data_class2 = frame2_new[frame2['Class']==2]
Data_class3 = frame2_new[frame2['Class']==3]
Data_class4 = frame2_new[frame2['Class']==4]
Data_class5 = frame2_new[frame2['Class']==5]
Data_class6 = frame2_new[frame2['Class']==6]
Data_class7 = frame2_new[frame2['Class']==7]

In [49]:
Std_Data_class1 = Standardisation(Data_class1)
Std_Data_class2 = Standardisation(Data_class2)
Std_Data_class3 = Standardisation(Data_class3)
Std_Data_class4 = Standardisation(Data_class4)
Std_Data_class5 = Standardisation(Data_class5)
Std_Data_class6 = Standardisation(Data_class6)
Std_Data_class7 = Standardisation(Data_class7)

In [50]:
n_class1 = len(Std_Data_class1)
n_class2 = len(Std_Data_class2)
n_class3 = len(Std_Data_class3)
n_class4 = len(Std_Data_class4)
n_class5 = len(Std_Data_class5)
n_class6 = len(Std_Data_class6)
n_class7 = len(Std_Data_class7)
n_class = 7
n_samples = len(Data_Q2)

i) Splitting frame2 into train and test splits T3 and T4, such that the samples in T3 are
the same as in T1. Considering T3 as training set, ignoring the Consumption column and considering
Class as labels, training a kernel SVM model with RBF kernel. Tuning gamma parameter using 5
fold cross-validation

In [51]:
frame2_concat = np.concatenate((Std_Data_class1,Std_Data_class2,Std_Data_class3,Std_Data_class4,Std_Data_class5,Std_Data_class6,Std_Data_class7),axis=0)
frame2_concat

array([[-1.69057515,  1.56332533, -0.50872666, -0.36562577, -1.92578217],
       [ 1.08329527, -1.52519545,  0.5814019 , -0.41227086, -1.30421035],
       [ 1.14473823, -1.54354096,  0.21802571, -0.39522746, -1.20606743],
       ...,
       [-0.05210673,  0.89556148,  1.58365011, -0.72120034,  1.75333848],
       [-0.72584916,  0.4976969 , -0.63676314, -0.72226637,  1.75333848],
       [ 0.41109119, -0.51563981, -0.63401056,  1.45428086,  1.75585334]])

In [52]:
frame2_concat = pd.DataFrame(frame2_concat, columns = ['Temperature', 'Humidity', 'Wind Speed', 'Flow', 'Consumption'])
frame2_concat['Class'] = frame2['Class'] 

In [53]:
T3, T4= train_test_split(frame2_concat, test_size = 0.20, random_state=42)

In [54]:
T3_X = T3.drop(['Consumption','Class'],axis=1)
T3_y = T3['Class']
T4_X = T4.drop(['Consumption','Class'],axis=1)
T4_y = T4['Class']

In [55]:
T3_y_consumption = T3.drop(['Temperature', 'Humidity', 'Wind Speed', 'Flow','Class'],axis=1)
T4_y_consumption = T4.drop(['Temperature', 'Humidity', 'Wind Speed', 'Flow','Class'],axis=1)

In [56]:
print("No of samples which have Class 1 = ", n_class1)
print("No of samples which have Class 2 = ", n_class2)
print("No of samples which have Class 3 = ", n_class3)
print("No of samples which have Class 4 = ", n_class4)
print("No of samples which have Class 5 = ", n_class5)
print("No of samples which have Class 6 = ", n_class6)
print("No of samples which have Class 7 = ", n_class7)

No of samples which have Class 1 =  15
No of samples which have Class 2 =  27
No of samples which have Class 3 =  103
No of samples which have Class 4 =  218
No of samples which have Class 5 =  280
No of samples which have Class 6 =  255
No of samples which have Class 7 =  102


So , Yes Classes have imbalance issue.

In [57]:
weight_class1 = n_samples/(n_class*n_class1)
weight_class2 = n_samples/(n_class*n_class2)
weight_class3 = n_samples/(n_class*n_class3)
weight_class4 = n_samples/(n_class*n_class4)
weight_class5 = n_samples/(n_class*n_class5)
weight_class6 = n_samples/(n_class*n_class6)
weight_class7 = n_samples/(n_class*n_class7)
class_weights =  {1: weight_class1, 2: weight_class2, 3: weight_class3, 4: weight_class4, 5: weight_class5, 6: weight_class6, 7: weight_class7}

In [58]:
def kernel_SVM_RBF(X,y):
  param_grid = {'kernel': ['rbf'], 'gamma': np.logspace(-3,3,7)}
  class_weights =  {1: weight_class1, 2: weight_class2, 3: weight_class3, 4: weight_class4, 5: weight_class5, 6: weight_class6, 7: weight_class7}
  svc = svm.SVC(class_weight=class_weights)
  CV_svc = GridSearchCV(estimator=svc, param_grid=param_grid, cv= 5)
  CV_svc.fit(X, y)
  best_gamma = CV_svc.best_params_
  return best_gamma

In [59]:
print("Best gamma for T3 set = ",kernel_SVM_RBF(T3_X,T3_y))

Best gamma for T3 set =  {'gamma': 10.0, 'kernel': 'rbf'}


j) Now considering samples belonging to a particular class i in T3, building a kernel ridge
regression model with RBF kernel (ignoring the Class column for this task). Tuning gamma parameter
using 5 fold cross-validation restricted to samples belonging to only class i. Repeating this
for each class. 

In [60]:
T3_class1 = T3[frame2['Class']==1]
T3_class2 = T3[frame2['Class']==2]
T3_class3 = T3[frame2['Class']==3]
T3_class4 = T3[frame2['Class']==4]
T3_class5 = T3[frame2['Class']==5]
T3_class6 = T3[frame2['Class']==6]
T3_class7 = T3[frame2['Class']==7]

<ipython-input-60-02fd361c435d>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  T3_class1 = T3[frame2['Class']==1]
<ipython-input-60-02fd361c435d>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  T3_class2 = T3[frame2['Class']==2]
<ipython-input-60-02fd361c435d>:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  T3_class3 = T3[frame2['Class']==3]
<ipython-input-60-02fd361c435d>:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  T3_class4 = T3[frame2['Class']==4]
<ipython-input-60-02fd361c435d>:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  T3_class5 = T3[frame2['Class']==5]
<ipython-input-60-02fd361c435d>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  T3_class6 = T3[frame2['Class']==6]
<ipython-input-60-02fd361c435d>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
 

In [61]:
T3_class1_X = T3_class1.drop(['Consumption','Class'],axis=1)
T3_class1_y = T3_class1['Consumption']

T3_class2_X = T3_class2.drop(['Consumption','Class'],axis=1)
T3_class2_y = T3_class2['Consumption']

T3_class3_X = T3_class3.drop(['Consumption','Class'],axis=1)
T3_class3_y = T3_class3['Consumption']

T3_class4_X = T3_class4.drop(['Consumption','Class'],axis=1)
T3_class4_y = T3_class4['Consumption']

T3_class5_X = T3_class5.drop(['Consumption','Class'],axis=1)
T3_class5_y = T3_class5['Consumption']

T3_class6_X = T3_class6.drop(['Consumption','Class'],axis=1)
T3_class6_y = T3_class6['Consumption']

T3_class7_X = T3_class7.drop(['Consumption','Class'],axis=1)
T3_class7_y = T3_class7['Consumption']

In [62]:
print("Best gamma for Class 1 set = ",kernel_ridge(T3_class1_X,T3_class1_y))
print("Best gamma for Class 2 set = ",kernel_ridge(T3_class2_X,T3_class2_y))
print("Best gamma for Class 3 set = ",kernel_ridge(T3_class3_X,T3_class3_y))
print("Best gamma for Class 4 set = ",kernel_ridge(T3_class4_X,T3_class4_y))
print("Best gamma for Class 5 set = ",kernel_ridge(T3_class5_X,T3_class5_y))
print("Best gamma for Class 6 set = ",kernel_ridge(T3_class6_X,T3_class6_y))
print("Best gamma for Class 7 set = ",kernel_ridge(T3_class7_X,T3_class7_y))

Best gamma for Class 1 set =  1.0
Best gamma for Class 2 set =  1.0
Best gamma for Class 3 set =  0.01
Best gamma for Class 4 set =  10.0
Best gamma for Class 5 set =  100.0
Best gamma for Class 6 set =  10.0
Best gamma for Class 7 set =  10.0


k) For testing (or) inference, implementing the following procedure: for any sample, first
predicting the class label as j and then based on the class label j, using model Mj to predict the
Consumption value. Using this procedure, finding the RMSE values for T3 and T4.

In [63]:
svc1=svm.SVC(kernel = 'rbf',gamma=10,class_weight=class_weights)
svc1.fit(T3_X,T3_y)
T3_pred_class=svc1.predict(T3_X)
y_pred_T3 = []

for i in range(len(T3_pred_class)):
  if T3_pred_class[i] == 1:
    M1 = KernelRidge(kernel='rbf',gamma=1)
    M1.fit(T3_class1_X,T3_class1_y)
    y_pred_T3.append(M1.predict(T3_X))
  elif T3_pred_class[i] == 2:
    M2 = KernelRidge(kernel='rbf',gamma=1)
    M2.fit(T3_class2_X,T3_class2_y)
    y_pred_T3.append(M2.predict(T3_X))
  elif T3_pred_class[i] == 3:
    M3 = KernelRidge(kernel='rbf',gamma=0.01)
    M3.fit(T3_class3_X,T3_class3_y)
    y_pred_T3.append(M3.predict(T3_X))
  elif T3_pred_class[i] == 4:
    M4 = KernelRidge(kernel='rbf',gamma=10)
    M4.fit(T3_class4_X,T3_class4_y)
    y_pred_T3.append(M4.predict(T3_X))
  elif T3_pred_class[i] == 5:
    M5 = KernelRidge(kernel='rbf',gamma=100)
    M5.fit(T3_class5_X,T3_class5_y)
    y_pred_T3.append(M5.predict(T3_X))
  elif T3_pred_class[i] == 6:
    M6 = KernelRidge(kernel='rbf',gamma=10)
    M6.fit(T3_class6_X,T3_class6_y)
    y_pred_T3.append(M6.predict(T3_X))
  else:
    M7 = KernelRidge(kernel='rbf',gamma=10)
    M7.fit(T3_class7_X,T3_class7_y)
    y_pred_T3.append(M7.predict(T3_X))



T3_y_consumption_arr = T3_y_consumption.to_numpy()


sum_sq_residuals = 0
for i in range(len(y_pred_T3)): 
  sum_sq_residuals += (T3_y_consumption_arr[i][0]-y_pred_T3[i][0])**2

RMSE_T3 = np.sqrt(sum_sq_residuals)


sigma_yy = 0
y_bar = 0
for i in range(len(y_pred_T3)):
  y_bar += float(T3_y_consumption.iat[i,0])/len(y_pred_T3)
for i in range(len(y_pred_T3)): 
  y_i = float(T3_y_consumption.iat[i,0]) 
  sigma_yy += (y_i-y_bar)**2
R_sq_T3 = 1.0-sum_sq_residuals/sigma_yy
print("RMSE value on set T3 = ",RMSE_T3)
print("R^2 value on set T3 = ",R_sq_T3)

RMSE value on set T3 =  28.420132802352782
R^2 value on set T3 =  -0.007846005651128918


In [64]:
svc1=svm.SVC(kernel = 'rbf',gamma=10,class_weight=class_weights)
svc1.fit(T4_X,T4_y)
T4_pred_class=svc1.predict(T4_X)
y_pred_T4 = []

for i in range(len(T4_pred_class)):
  if T4_pred_class[i] == 1:
    y_pred_T4.append(M1.predict(T4_X))
  elif T4_pred_class[i] == 2:
    y_pred_T4.append(M2.predict(T4_X))
  elif T4_pred_class[i] == 3:
    y_pred_T4.append(M3.predict(T4_X))
  elif T4_pred_class[i] == 4:
    y_pred_T4.append(M4.predict(T4_X))
  elif T4_pred_class[i] == 5:
    y_pred_T4.append(M5.predict(T4_X))
  elif T4_pred_class[i] == 6:
    y_pred_T4.append(M6.predict(T4_X))
  else:
    y_pred_T4.append(M7.predict(T4_X))



T4_y_consumption_arr = T4_y_consumption.to_numpy()

sum_sq_residuals_T4 = 0
for i in range(len(y_pred_T4)): 
  sum_sq_residuals_T4 += (T4_y_consumption_arr[i][0]-y_pred_T4[i][0])**2

RMSE_T4 = np.sqrt(sum_sq_residuals_T4)


sigma_yy_T4 = 0
y_bar_T4 = 0
for i in range(len(y_pred_T4)):
  y_bar_T4 += float(T4_y_consumption.iat[i,0])/len(y_pred_T4)
for i in range(len(y_pred_T4)): 
  y_i_T4 = float(T4_y_consumption.iat[i,0]) 
  sigma_yy_T4 += (y_i_T4-y_bar_T4)**2
R_sq_T4 = 1.0-(sum_sq_residuals_T4/sigma_yy_T4)
print("RMSE value on set T4 = ",RMSE_T4)
print("R^2 value on set T4 = ",R_sq_T4)

RMSE value on set T4 =  13.996001896490897
R^2 value on set T4 =  0.008937038203345238


l) Compare and contrast the RMSE values obtained in part (f) and part (k). Using
your observations, suggest when the two-stage approach of classification-followed-by-regression
would be useful when compared to the simple regression approach on the full data set.

In [65]:
print("RMSE value on the training set T1 = ",RMSE_T1)
print("R^2 value on the training set T1 = ",r2_T1)
print("RMSE value on the test set T2 = ",RMSE_T2)
print("R^2 value on the test set T2 = ",r2_T2)
print("RMSE value on set T3 = ",RMSE_T3)
print("R^2 value on set T3 = ",R_sq_T3)
print("RMSE value on set T4 = ",RMSE_T4)
print("R^2 value on set T4 = ",R_sq_T4)

RMSE value on the training set T1 =  0.6500917245076449
R^2 value on the training set T1 =  0.5853383919265936
RMSE value on the test set T2 =  0.8128918014697996
R^2 value on the test set T2 =  0.2820379758920609
RMSE value on set T3 =  28.420132802352782
R^2 value on set T3 =  -0.007846005651128918
RMSE value on set T4 =  13.996001896490897
R^2 value on set T4 =  0.008937038203345238


In part (f), we trained a kernel ridge regression model on the entire dataset, while in part (k), we used a two-stage approach of first predicting the class label using an kernel SVM model with RBF kernel and then using a  kernel ridge regression model for the corresponding class to predict the Consumption value.

The RMSE values obtained in part (f) were very low for T3 and T4 (<1), while in part (k), the RMSE values are very high for T3 and T4. Thus, the two-stage approach resulted in higher RMSE values for both T3 and T4. This is because,
in two-stage approach of classification-followed-by-regression, the classification model is not able to accurately predict the class labels for all samples, leading to incorrect regression models being used for some samples.







I think, the two-stage approach of classification-followed-by-regression
would be useful  compared to the simple regression approach on the full data set when, the classification model is able to accurately predict the class labels for all samples or the dataset have clear class boundaries or the number of samples per class are balanced or the hyperparameters of the classification and regression models are tuned optimally.